### ISSUE TITLE
Plugin stopped working after upgrading Kibana from 6.5.4 to 6.6.0

### ISSUE THREAD

**Issue by yann-soubeyrand** [bitsensor/elastalert-kibana-plugin#94]
Hi,

After upgrading Kibana from 6.5.4 to 6.6.0, Elastalert plugin stopped working. Here is the message we get in the logs:
```
Debug: internal, implementation, error 
    TypeError: callback is not a function
    at Object.mapUri (/usr/share/kibana/plugins/elastalert-kibana-plugin/server/routes/elastalert.js:11:11)
    at /usr/share/kibana/node_modules/h2o2/lib/index.js:87:49
    at module.exports.internals.Manager.execute (/usr/share/kibana/node_modules/hapi/lib/toolkit.js:35:106)
    at Object.internals.handler (/usr/share/kibana/node_modules/hapi/lib/handler.js:50:48)
    at exports.execute (/usr/share/kibana/node_modules/hapi/lib/handler.js:35:36)
    at Request._lifecycle (/usr/share/kibana/node_modules/hapi/lib/request.js:263:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by martijnrondeel** [comment]
Version 1.0.2 can be downloaded now from the [releases page](https://github.com/bitsensor/elastalert-kibana-plugin/releases) and supports Kibana 6.6.0 and higher.

**Comment by yann-soubeyrand** [comment]
I confirm it's working again ;-)

Thanks!

**Comment by venusf1ytrap** [comment]
Plugin installation was unsuccessful due to error "Plugin elastalert-kibana-plugin [6.6.0] is incompatible with Kibana [6.6.2]

I get the following message. Any idea how do i resolve this ?

**Comment by yann-soubeyrand** [comment]
@venusf1ytrap I think using version 6.6.2 of the plugin (https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.2/elastalert-kibana-plugin-1.0.2-6.6.2.zip) should help (plugin must be at the exact same version than Kibana) ;-)
